### ISSUE TITLE
Can't SSH into 'novnc' container.

### ISSUE THREAD

**Issue by thirdbyte** [BlackArch/blackarch-docker#5]
Command used to run the container:
$ docker run --rm -itd -p8080:8080 -p22:22 --security-opt seccomp=unconfined blackarchlinux/blackarch:novnc

Supervisord is running SSHd but no root password is set due to which a user can not SSH into the container.

**Comment by thirdbyte** [comment]
Even if a root password gets initiated in the Dockerfile, the /etc/ssh/sshd_config might need to be initialized as well for SSH to work.

**Comment by noraj** [comment]
## In general

Docker containers are meant to run only one service, multi-service apps use docker-compose tun run each service in a different container. It's still possible to use supervisord like you did to run several services in the same container but it's not recommended, in most cases you should either use docker-compose or a VM.

## Your case

Here you want to run a service + SSH. The first question is why? If you want to debug your container you can have a shell with `docker exec -it containerid /bin/bash` or `docker attach containerid`. If it's for long term deployment on a VPS you should install ArchLinux as host and install BlackArch repositories on top of it. If it's for long term deployment on your machine you should use a VM instead of a container. I don't see a recommended use case for SSH in a BlackArch container.

## If you still want to do it

Most linux containers will have the same issue that you had here, and it's normal.

If you still want to SSH in a BA container it will be up to you to write a `Dockerfile`, to setup a password for the root account or create another account and maybe to modify the SSHd config to yoru needs, eg. for ubuntu https://dev.to/s1ntaxe770r/how-to-setup-ssh-within-a-docker-container-i5i.

**Comment by thirdbyte** [comment]
@noraj Then Dockerfile must be updated to remove the openssh package and exposed 22 port and supervisord.conf must also be updated to remove the ssh specific sections. It's just being an overhead to the image.

**Comment by noraj** [comment]
In my opinion the noVNC image is a non-sense and should be removed. When having 10 services, a graphical server, etc. it's a VM that is required (or something like [nspawn](https://wiki.archlinux.org/title/Systemd-nspawn)) not a container.

**Comment by noraj** [comment]
@noptrix Should we remove the novnc image?

**Comment by thirdbyte** [comment]
> @noptrix Should we remove the novnc image?

The image should be removed in my opinion. I'm personally more interested in systemd-nspawn. Maybe a dedicated repository with a guide on setting up a BlackArch nspawn container would be a great helpful since there's aren't sufficient resources on the use of nspawn.

**Comment by noraj** [comment]
I not sure it's documented somewhere yet but I remember there is a nspawn image for BA: https://hub.nspawn.org/images/

**Comment by ikstream** [comment]
The novnc image was added on special request, therefore I am strongly opposed to it's removal. 

The openssh package is also an ssh client and has been added for that purpose afaik.




They also provide a wrapper around [nspawn](https://github.com/nspawn/nspawn) provides a wrapper around machinectl to ease it's usage and as @noraj pointed out, a BlackArch image is also provided

**Comment by thirdbyte** [comment]
@ikstream It's totally cool if the novnc image is here to live. I see the issue got closed again. Let me clarify the initial issue once again. When I run the blackarchlinux/blackarch:novnc image using the command:

`$ docker run --rm -itd -p8080:8080 -p22:22 --security-opt seccomp=unconfined blackarchlinux/blackarch:novnc`

I can absolutely access the NoVNC service when I visit localhost:8080 from a web browser. But, when I try to connect using SSH with:

`$ ssh root@localhost`

I get the initial host verification prompt and then after a 'yes' I need to enter a password.

There are two issues. 
1. The image should either be initiated with a default root password (like blackarch) so that a user can SSH into the container.
2. The /etc/ssh/sshd_config needs to have `PermitRootLogin yes` for SSH to work.

If I Initiate a password using `passwd` command from VNC session and then add `PermitRootLogin` to /etc/ssh/sshd_config, I can successfully SSH into the container from my host using the initiated password. But these two things should come preconfigured in the image itself.

**Comment by ikstream** [comment]
I see, I am currently on vacation, but will take care of it in the coming week
